[project]
name = "trip-service-kata"
version = "0.1.0"
description = "Testing legacy code: Hard-wired dependencies"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
